version: "3.8"
services:
  node:
    image: node:8
    user: node
    working_dir: /home/node/app
    environment:
      - NODE_ENV=${ENVIRONMENT}
    volumes:
      - ./:/home/node/app
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    command: yarn start
  db:
    image: postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - database-data:/var/lib/postgresql/data/

volumes:
  database-data: